sudo: required

services:
  - docker
  
before_install:
 - docker login --username=$U --password=$P
 
script: 
 - docker build -t infrastructor/centos-sshd:0.0.2 . 
 - docker tag infrastructor/centos-sshd:latest infrastructor/centos-sshd:0.0.2
 - docker push infrastructor/centos-sshd:0.0.2
 - docker push infrastructor/centos-sshd:latest
