sudo: required

services:
  - docker
  
before_install:
 - docker login --username=$U --password=$P
 
script: 
 - docker build -t infrastructor/centos-sshd . 
 - docker tag infrastructor/centos-sshd infrastructor/centos-sshd:0.0.4
 - docker tag infrastructor/centos-sshd infrastructor/centos-sshd:latest
 - docker push infrastructor/centos-sshd:0.0.4
 - docker push infrastructor/centos-sshd:latest
